//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoveryThisFile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecoveryThisFile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button1 {
            get {
                object obj = ResourceManager.GetObject("button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chosse {
            get {
                object obj = ResourceManager.GetObject("chosse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goback {
            get {
                object obj = ResourceManager.GetObject("goback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scanner {
            get {
                object obj = ResourceManager.GetObject("scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screen {
            get {
                object obj = ResourceManager.GetObject("screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string strB {
            get {
                return ResourceManager.GetString("strB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover File....
        /// </summary>
        internal static string strButton {
            get {
                return ResourceManager.GetString("strButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover Files....
        /// </summary>
        internal static string strButton1 {
            get {
                return ResourceManager.GetString("strButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good (no lost data detected).
        /// </summary>
        internal static string strChance {
            get {
                return ResourceManager.GetString("strChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good (data may be overwritten).
        /// </summary>
        internal static string strChance1 {
            get {
                return ResourceManager.GetString("strChance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad (data is partially overwritten).
        /// </summary>
        internal static string strChance2 {
            get {
                return ResourceManager.GetString("strChance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad (data is completely overwritten).
        /// </summary>
        internal static string strChance3 {
            get {
                return ResourceManager.GetString("strChance3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string strChance4 {
            get {
                return ResourceManager.GetString("strChance4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        internal static string strChance5 {
            get {
                return ResourceManager.GetString("strChance5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        internal static string strE {
            get {
                return ResourceManager.GetString("strE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;How to use Scan by types feature?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp10 {
            get {
                return ResourceManager.GetString("strHelp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on Scan by types button and do the same as Scan all and Scan by name button. However please note:.
        /// </summary>
        internal static string strHelp11 {
            get {
                return ResourceManager.GetString("strHelp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Scan by types&lt;/b&gt; feature will help you search all deleted files by file types.&lt;/p&gt; Access this feature from:  &lt;b&gt;Undo It &lt;/b&gt;&lt;b&gt;&gt; &lt;/b&gt;&lt;b&gt;Scan by types :&lt;/b&gt;.
        /// </summary>
        internal static string strHelp12 {
            get {
                return ResourceManager.GetString("strHelp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;left&quot;&gt;You don’t need to type in file name. Just select the Disk and select the icon that represents for the file type you want to find or click on &lt;b&gt;Choice&lt;/b&gt; icon to find other file types.&lt;/span&gt;.
        /// </summary>
        internal static string strHelp13 {
            get {
                return ResourceManager.GetString("strHelp13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Recover This File app works best if performed as soon as possible after file deletion.&lt;/p&gt;
        ///When you delete a file, the data is not lost - but new files being written to the hard drive may overwrite your data permanently, making recovery impossible..
        /// </summary>
        internal static string strHelp14 {
            get {
                return ResourceManager.GetString("strHelp14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If, for any reasons, you are not happy with our app, please also contact us at: &lt;a href=&quot;mailto:recoverthisfile@gmail.com&quot;&gt;recoverthisfile@gmail.com&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Our support page: &lt;a href=&quot;http://recoverthisfile.com/support&quot; class=&quot;alert-link&quot;&gt;http://recoverthisfile.com/support&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Email our support team at : &lt;a href=&quot;mailto:recoverthisfile@gmail.com&quot;&gt;recoverthisfile@gmail.com&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string strHelp15 {
            get {
                return ResourceManager.GetString("strHelp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span align=&quot;center&quot;&gt;&lt;h3&gt;Recover This File&lt;/h3&gt;&lt;/span&gt;&lt;/p&gt;
        ///Thank you for downloading Recover This File app, a product of IPcamsoft.com. Recover This File is a fully featured, file recovery tool for Windows. Accidentally deleted a file? Never fear; the data is probably still on your drive and may be recoverable. Undo It finds all of the deleted files on your hard drive, flash drive or SD card and allows you to recover them..
        /// </summary>
        internal static string strHelp16 {
            get {
                return ResourceManager.GetString("strHelp16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;How to use Scan all feature?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp4 {
            get {
                return ResourceManager.GetString("strHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Scan all&lt;/b&gt; feature will help you search all deleted files. Access this feature from: &lt;b&gt;Undo It &lt;/b&gt;&lt;b&gt;&gt; &lt;/b&gt;&lt;b&gt;Scan all :&lt;/b&gt;.
        /// </summary>
        internal static string strHelp5 {
            get {
                return ResourceManager.GetString("strHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt; &gt;&lt;/b&gt; Firstly, click on &lt;b&gt;Scan all&lt;/b&gt; button&lt;/p&gt;
        ///&lt;b&gt; &gt;&lt;/b&gt; You can browse by one of your Disks or Folder. Check on &lt;b&gt;Select All Disks&lt;/b&gt; box if you want to scan  all of your Disks at a time.
        ///&lt;b&gt; &gt;&lt;/b&gt; And then click &lt;b&gt;Scan&lt;/b&gt; button to start scanning.
        ///&lt;div&gt;
        ///                         &lt;p&gt;Click &lt;b&gt;Stop&lt;/b&gt; button at any time when you want to stop scanning.&lt;/p&gt;
        ///                         &lt;p&gt;After finished scanning, you can type the keyword (file name) in the Search box to be able to find your fil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strHelp6 {
            get {
                return ResourceManager.GetString("strHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;How to use Scan by name feature?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp7 {
            get {
                return ResourceManager.GetString("strHelp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Scan by name&lt;/b&gt; feature will help you search all deleted files by file name.&lt;/p&gt;Access this feature from: &lt;b&gt;Undo It &lt;/b&gt;&lt;b&gt;&gt; &lt;/b&gt;&lt;b&gt;Scan by name :&lt;/b&gt;.
        /// </summary>
        internal static string strHelp8 {
            get {
                return ResourceManager.GetString("strHelp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;left&quot;&gt;Click on Scan by name button and do the same steps as Scan all button. But there are some differences as below:
        ///Type the file name before scanning. (If you cannot remember the correct name, just type in the first letter of the name for scanning similar files)&lt;/span&gt;.
        /// </summary>
        internal static string strHelp9 {
            get {
                return ResourceManager.GetString("strHelp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;Some wheelie good advice for you:&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpAD {
            get {
                return ResourceManager.GetString("strHelpAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+12&quot;&gt;Contact us&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpCS {
            get {
                return ResourceManager.GetString("strHelpCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;User manual&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpUS {
            get {
                return ResourceManager.GetString("strHelpUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to save the file to the same location with its old location. This may cause the recovery failed and overwrite your data permanently. Are you sure you want to continue.
        /// </summary>
        internal static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until recovery is finished..
        /// </summary>
        internal static string strMessage1 {
            get {
                return ResourceManager.GetString("strMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft PowerPoint.
        /// </summary>
        internal static string strP {
            get {
                return ResourceManager.GetString("strP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        internal static string strP3 {
            get {
                return ResourceManager.GetString("strP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4.
        /// </summary>
        internal static string strP4 {
            get {
                return ResourceManager.GetString("strP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe PDF.
        /// </summary>
        internal static string strPD {
            get {
                return ResourceManager.GetString("strPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word.
        /// </summary>
        internal static string strW {
            get {
                return ResourceManager.GetString("strW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
