//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoveryThisFile.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ge {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ge() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecoveryThisFile.Language.ge", typeof(ge).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_3 {
            get {
                object obj = ResourceManager.GetObject("all_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("all_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_black {
            get {
                object obj = ResourceManager.GetObject("all_x128_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button1 {
            get {
                object obj = ResourceManager.GetObject("button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chosse {
            get {
                object obj = ResourceManager.GetObject("chosse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img2 {
            get {
                object obj = ResourceManager.GetObject("img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img3 {
            get {
                object obj = ResourceManager.GetObject("img3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3 {
            get {
                object obj = ResourceManager.GetObject("name_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("name_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("name_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1 {
            get {
                object obj = ResourceManager.GetObject("option_x128_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1_black {
            get {
                object obj = ResourceManager.GetObject("option_x128_1_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1_hv {
            get {
                object obj = ResourceManager.GetObject("option_x128_1_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_1 {
            get {
                object obj = ResourceManager.GetObject("pc_x128_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_1_hv {
            get {
                object obj = ResourceManager.GetObject("pc_x128_1_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("pc_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scanner {
            get {
                object obj = ResourceManager.GetObject("scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screen {
            get {
                object obj = ResourceManager.GetObject("screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erlesen alle disketten.
        /// </summary>
        internal static string strAlldisk {
            get {
                return ResourceManager.GetString("strAlldisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchsuchen.
        /// </summary>
        internal static string strB {
            get {
                return ResourceManager.GetString("strB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retten Datei....
        /// </summary>
        internal static string strButton {
            get {
                return ResourceManager.GetString("strButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retten Dateien....
        /// </summary>
        internal static string strButton1 {
            get {
                return ResourceManager.GetString("strButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zurückstellen Dateien.
        /// </summary>
        internal static string strButton2 {
            get {
                return ResourceManager.GetString("strButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gut (Keine verlorenen Daten erkannt).
        /// </summary>
        internal static string strChance {
            get {
                return ResourceManager.GetString("strChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gut (Daten können überschrieben werden).
        /// </summary>
        internal static string strChance1 {
            get {
                return ResourceManager.GetString("strChance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schlecht (Daten werden teilweise überschrieben).
        /// </summary>
        internal static string strChance2 {
            get {
                return ResourceManager.GetString("strChance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schlecht (Daten werden vollständig überschrieben).
        /// </summary>
        internal static string strChance3 {
            get {
                return ResourceManager.GetString("strChance3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        internal static string strChance4 {
            get {
                return ResourceManager.GetString("strChance4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgezeichnet.
        /// </summary>
        internal static string strChance5 {
            get {
                return ResourceManager.GetString("strChance5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beitreibungschancen.
        /// </summary>
        internal static string strChances {
            get {
                return ResourceManager.GetString("strChances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auserwählen Dateityp.
        /// </summary>
        internal static string strChoose {
            get {
                return ResourceManager.GetString("strChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computerinformationen.
        /// </summary>
        internal static string strcp {
            get {
                return ResourceManager.GetString("strcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerkonto.
        /// </summary>
        internal static string strcpAC {
            get {
                return ResourceManager.GetString("strcpAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Ausweis.
        /// </summary>
        internal static string strcpMAc {
            get {
                return ResourceManager.GetString("strcpMAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Computer.
        /// </summary>
        internal static string strcpName {
            get {
                return ResourceManager.GetString("strcpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prozessor.
        /// </summary>
        internal static string strcpProcess {
            get {
                return ResourceManager.GetString("strcpProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installiert speicher.
        /// </summary>
        internal static string strcpRam {
            get {
                return ResourceManager.GetString("strcpRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        internal static string strE {
            get {
                return ResourceManager.GetString("strE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine E-mail.
        /// </summary>
        internal static string strEmail {
            get {
                return ResourceManager.GetString("strEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string strEnglish {
            get {
                return ResourceManager.GetString("strEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgang.
        /// </summary>
        internal static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateiname.
        /// </summary>
        internal static string strFilename {
            get {
                return ResourceManager.GetString("strFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateityp.
        /// </summary>
        internal static string strFileType {
            get {
                return ResourceManager.GetString("strFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertige Scannen...!.
        /// </summary>
        internal static string strFinished {
            get {
                return ResourceManager.GetString("strFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzeichnis Adresse.
        /// </summary>
        internal static string strFolder {
            get {
                return ResourceManager.GetString("strFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abkömmlich.
        /// </summary>
        internal static string strFree {
            get {
                return ResourceManager.GetString("strFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string strFrench {
            get {
                return ResourceManager.GetString("strFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche.
        /// </summary>
        internal static string strGerman {
            get {
                return ResourceManager.GetString("strGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Festplatte.
        /// </summary>
        internal static string strHardware {
            get {
                return ResourceManager.GetString("strHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;Wie benutzt man Einscannen von bauart?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp10 {
            get {
                return ResourceManager.GetString("strHelp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Einscannen by bauart button und Tue das gleiche wie Einscannen allen und Einscannen namentlich.
        /// Bitte beachten sie jedoch:.
        /// </summary>
        internal static string strHelp11 {
            get {
                return ResourceManager.GetString("strHelp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Einscannen by bauart:&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp12 {
            get {
                return ResourceManager.GetString("strHelp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span align=&quot;left&quot;&gt;Sie müssen den Dateinamen nicht eingeben. Wählen Sie einfach die Festplatte aus and Wählen Sie das symbol aus, das den Dateityp darstellt Sie wollen finden oder Klicke auf &lt;b&gt;Wahl&lt;/b&gt; symbol, um andere Dateitypen zu finden.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp13 {
            get {
                return ResourceManager.GetString("strHelp13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Undo It App funktioniert am besten, wenn sie so schnell wie möglich nach dem Löschen der Datei ausgeführt wird. &lt;/p&gt;
        ///Wenn Sie eine Datei löschen, werden die Daten nicht verloren - aber neue Dateien, die auf die Festplatte geschrieben werden, können Ihre Daten dauerhaft überschreiben und die Wiederherstellung unmöglich machen..
        /// </summary>
        internal static string strHelp14 {
            get {
                return ResourceManager.GetString("strHelp14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;kontaktiere uns unter: &lt;a href=&quot;mailto:support@ipcamsoft.com&quot;&gt;support@ipcamsoft.com&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Unsere Support-Seite: &lt;a href=&quot;http://ipcamsoft.com/support&quot; class=&quot;alert-link&quot;&gt;http://ipcamsoft.com/support&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;E-mail Sie unser Support-Team unter: &lt;a href=&quot;mailto:support@ipcamsoft.com&quot;&gt;support@ipcamsoft.com&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string strHelp15 {
            get {
                return ResourceManager.GetString("strHelp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span align=&quot;center&quot;&gt;&lt;h3&gt;Undo It&lt;/h3&gt;&lt;/span&gt;&lt;/p&gt;
        ///Undo It ist ein großartiger Dateiwiederherstellenprogramm Das wird helfen, sich zu erholen Ihre gelöschten Dateien Schnell und einfach.
        ///
        ///Dieser Leitfaden wird Ihnen helfen Erfahren sie wie sie beginnen verwendung der Anwendung leicht..
        /// </summary>
        internal static string strHelp16 {
            get {
                return ResourceManager.GetString("strHelp16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;Wie benutzt man Einscannen allen?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp4 {
            get {
                return ResourceManager.GetString("strHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Einscannen allen&lt;/b&gt; Suche alle gelöschten Dateien.
        /// </summary>
        internal static string strHelp5 {
            get {
                return ResourceManager.GetString("strHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt; &gt;&lt;/b&gt; Zuerst klicken auf &lt;b&gt;Einscannen allen&lt;/b&gt; Taste&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt; &gt;&lt;/b&gt; Sie können durch eine Ihrer Festplatten oder Ordner durchsuchen. Prüfen auf &lt;b&gt;Erlesen alle disketten&lt;/b&gt; feld Wenn Sie alle Ihre Festplatten gleichzeitig scannen möchten.&lt;/p&gt;
        ///&lt;b&gt; &gt;&lt;/b&gt; Und dann klicke &lt;b&gt;Einscannen&lt;/b&gt; Taste zum Scannen starten.
        ///&lt;div&gt;
        ///                         &lt;p&gt;klicke &lt;b&gt;Halt&lt;/b&gt; Taste jederzeitwenn du willst stoppen Sie das Scannen..&lt;/p&gt;
        ///                         Nach dem Scannen, Sie können das Schlüsselw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strHelp6 {
            get {
                return ResourceManager.GetString("strHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;Wie benutzt man Einscannen namentlich?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp7 {
            get {
                return ResourceManager.GetString("strHelp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Einscannen namentlich:&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp8 {
            get {
                return ResourceManager.GetString("strHelp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;/p&gt;
        ///&lt;span align=&quot;left&quot;&gt;Klicke auf Einscannen namentlich taste und mach die gleichen Schritte wie Einscannen allen taste. Aber es gibt einige unterschiede unten:
        ///	Geben Sie den Dateinamen vor dem Scannen ein. (Wenn du dich nicht erinnern kannst den richtigen Namen, Geben Sie einfach den ersten Buchstaben des Namens ein zum scannen ähnlicher Dateien)&lt;/span&gt;.
        /// </summary>
        internal static string strHelp9 {
            get {
                return ResourceManager.GetString("strHelp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;einige Ratschläge:&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpAD {
            get {
                return ResourceManager.GetString("strHelpAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+12&quot;&gt;Kontaktieren Sie uns&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpCS {
            get {
                return ResourceManager.GetString("strHelpCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;Bedienungsanleitung&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpUS {
            get {
                return ResourceManager.GetString("strHelpUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string strJapanese {
            get {
                return ResourceManager.GetString("strJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachen.
        /// </summary>
        internal static string strLanguage {
            get {
                return ResourceManager.GetString("strLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Später.
        /// </summary>
        internal static string strLater {
            get {
                return ResourceManager.GetString("strLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einen Speicherstelle auswählen.
        /// </summary>
        internal static string strlocation {
            get {
                return ResourceManager.GetString("strlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du versuchst es zu speicher die Datei  an der gleichen Stelle mit seiner alten Lage. Dies kann dazu führen der wiederherstellungsfehler und Überschreiben Sie Ihre Daten dauerhaft.   Sind Sie sicher, dass Sie fortfahren möchten?.
        /// </summary>
        internal static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warten Sie bitte, bis die Wiederherstellung vollständig fertiggestellt ist..
        /// </summary>
        internal static string strMessage1 {
            get {
                return ResourceManager.GetString("strMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte registrieren zu fähig sein anwenden dieses Funktion.
        /// </summary>
        internal static string strMessage10 {
            get {
                return ResourceManager.GetString("strMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warten Sie bitte, bis die Wiederherstellung vollständig fertiggestellt ist..
        /// </summary>
        internal static string strMessage11 {
            get {
                return ResourceManager.GetString("strMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie fortfahren möchten?.
        /// </summary>
        internal static string strMessage12 {
            get {
                return ResourceManager.GetString("strMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Version ist jederzeit zu haben. Möchtest du jetzt aktualisieren?.
        /// </summary>
        internal static string strMessage13 {
            get {
                return ResourceManager.GetString("strMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pardon. Bitte auswählen dateityp vor dem Scannen!.
        /// </summary>
        internal static string strMessage14 {
            get {
                return ResourceManager.GetString("strMessage14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie den ein dateinamen vor dem Scannen!.
        /// </summary>
        internal static string strMessage15 {
            get {
                return ResourceManager.GetString("strMessage15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wählen Sie ein Laufwerk oder Verzeichnis an Laufwerk vor dem Scannen!.
        /// </summary>
        internal static string strMessage16 {
            get {
                return ResourceManager.GetString("strMessage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach Dateinamen hier.
        /// </summary>
        internal static string strMessage17 {
            get {
                return ResourceManager.GetString("strMessage17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;center&quot;&gt;Applikationssoftware ist im abscannen-verfahren. Sind Sie sicher, dass Sie hör auf möchten?
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strMessage2 {
            get {
                return ResourceManager.GetString("strMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;center&quot;&gt;Applikationssoftware ist im abscannen-verfahren . Sind Sie sicher, dass Sie beenden möchten?
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strMessage3 {
            get {
                return ResourceManager.GetString("strMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pardon. Bitte überprüfen Sie das format des eingegeben  E-Mail-Adresse!.
        /// </summary>
        internal static string strMessage4 {
            get {
                return ResourceManager.GetString("strMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordnungsnummer feld darf nicht leer sein.
        /// </summary>
        internal static string strMessage5 {
            get {
                return ResourceManager.GetString("strMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email feld darf nicht leer sein..
        /// </summary>
        internal static string strMessage6 {
            get {
                return ResourceManager.GetString("strMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte erneut versuchen. Der E-mail-addresse oder Ordnungsnummer deine unterstützte Das ist nicht richtig..
        /// </summary>
        internal static string strMessage7 {
            get {
                return ResourceManager.GetString("strMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrierung erfolgreich.
        /// </summary>
        internal static string strMessage8 {
            get {
                return ResourceManager.GetString("strMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte eingeben email und ordnungsnummer.
        /// </summary>
        internal static string strMessage9 {
            get {
                return ResourceManager.GetString("strMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte modifizierte.
        /// </summary>
        internal static string strModified {
            get {
                return ResourceManager.GetString("strModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordnungsnummer.
        /// </summary>
        internal static string strNumber {
            get {
                return ResourceManager.GetString("strNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anfang der Zeit.
        /// </summary>
        internal static string strOption {
            get {
                return ResourceManager.GetString("strOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Vierteljahr.
        /// </summary>
        internal static string strOption1 {
            get {
                return ResourceManager.GetString("strOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Woche.
        /// </summary>
        internal static string strOption2 {
            get {
                return ResourceManager.GetString("strOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scannen Sie die folgenden Elemente von letzte modifizierte von:.
        /// </summary>
        internal static string strOption3 {
            get {
                return ResourceManager.GetString("strOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahr.
        /// </summary>
        internal static string strOption4 {
            get {
                return ResourceManager.GetString("strOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jahre.
        /// </summary>
        internal static string strOption4a {
            get {
                return ResourceManager.GetString("strOption4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string strOption5 {
            get {
                return ResourceManager.GetString("strOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionen.
        /// </summary>
        internal static string strOption6 {
            get {
                return ResourceManager.GetString("strOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft PowerPoint.
        /// </summary>
        internal static string strP {
            get {
                return ResourceManager.GetString("strP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        internal static string strP3 {
            get {
                return ResourceManager.GetString("strP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4.
        /// </summary>
        internal static string strP4 {
            get {
                return ResourceManager.GetString("strP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weg.
        /// </summary>
        internal static string strPath {
            get {
                return ResourceManager.GetString("strPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe PDF.
        /// </summary>
        internal static string strPD {
            get {
                return ResourceManager.GetString("strPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to käuflich erwerben eben.
        /// </summary>
        internal static string strPurchase {
            get {
                return ResourceManager.GetString("strPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erholend.
        /// </summary>
        internal static string strRecovering {
            get {
                return ResourceManager.GetString("strRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekommandieren.
        /// </summary>
        internal static string strRegister {
            get {
                return ResourceManager.GetString("strRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absaven.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einscannen.
        /// </summary>
        internal static string strScan {
            get {
                return ResourceManager.GetString("strScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchanfrage.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größe.
        /// </summary>
        internal static string strSize {
            get {
                return ResourceManager.GetString("strSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string strSpanish {
            get {
                return ResourceManager.GetString("strSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        internal static string strStop {
            get {
                return ResourceManager.GetString("strStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haltend.
        /// </summary>
        internal static string strStopping {
            get {
                return ResourceManager.GetString("strStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ.
        /// </summary>
        internal static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        internal static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to benutzt.
        /// </summary>
        internal static string strUsed {
            get {
                return ResourceManager.GetString("strUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word.
        /// </summary>
        internal static string strW {
            get {
                return ResourceManager.GetString("strW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        internal static string strWarning {
            get {
                return ResourceManager.GetString("strWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3 {
            get {
                object obj = ResourceManager.GetObject("types_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("types_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("types_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
