//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoveryThisFile.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ja() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecoveryThisFile.Language.ja", typeof(ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_blue_backgrounds_40_1920x1200_71456 {
            get {
                object obj = ResourceManager.GetObject("abstract_blue_backgrounds_40_1920x1200_71456", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_3 {
            get {
                object obj = ResourceManager.GetObject("all_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("all_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_black {
            get {
                object obj = ResourceManager.GetObject("all_x128_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button1 {
            get {
                object obj = ResourceManager.GetObject("button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chosse {
            get {
                object obj = ResourceManager.GetObject("chosse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img2 {
            get {
                object obj = ResourceManager.GetObject("img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img3 {
            get {
                object obj = ResourceManager.GetObject("img3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3 {
            get {
                object obj = ResourceManager.GetObject("name_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("name_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("name_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1 {
            get {
                object obj = ResourceManager.GetObject("option_x128_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1_black {
            get {
                object obj = ResourceManager.GetObject("option_x128_1_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1_hv {
            get {
                object obj = ResourceManager.GetObject("option_x128_1_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_1 {
            get {
                object obj = ResourceManager.GetObject("pc_x128_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_1_hv {
            get {
                object obj = ResourceManager.GetObject("pc_x128_1_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("pc_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scanner {
            get {
                object obj = ResourceManager.GetObject("scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screen {
            get {
                object obj = ResourceManager.GetObject("screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべてのディスクを選択します。.
        /// </summary>
        internal static string strAlldisk {
            get {
                return ResourceManager.GetString("strAlldisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウズ.
        /// </summary>
        internal static string strB {
            get {
                return ResourceManager.GetString("strB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを回復する。.
        /// </summary>
        internal static string strButton {
            get {
                return ResourceManager.GetString("strButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを回復する。.
        /// </summary>
        internal static string strButton1 {
            get {
                return ResourceManager.GetString("strButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルを復元する。.
        /// </summary>
        internal static string strButton2 {
            get {
                return ResourceManager.GetString("strButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 良い (失われたデータ検出).
        /// </summary>
        internal static string strChance {
            get {
                return ResourceManager.GetString("strChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 良い(データを上書き可能性があります) 。.
        /// </summary>
        internal static string strChance1 {
            get {
                return ResourceManager.GetString("strChance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 悪い (データは部分的に上書きされます) 。.
        /// </summary>
        internal static string strChance2 {
            get {
                return ResourceManager.GetString("strChance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 悪い  (データを完全に上書き) 。.
        /// </summary>
        internal static string strChance3 {
            get {
                return ResourceManager.GetString("strChance3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明.
        /// </summary>
        internal static string strChance4 {
            get {
                return ResourceManager.GetString("strChance4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 優れた.
        /// </summary>
        internal static string strChance5 {
            get {
                return ResourceManager.GetString("strChance5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回復のチャンス.
        /// </summary>
        internal static string strChances {
            get {
                return ResourceManager.GetString("strChances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの種類を選択します。.
        /// </summary>
        internal static string strChoose {
            get {
                return ResourceManager.GetString("strChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンピューター情報.
        /// </summary>
        internal static string strcp {
            get {
                return ResourceManager.GetString("strcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー アカウント.
        /// </summary>
        internal static string strcpAC {
            get {
                return ResourceManager.GetString("strcpAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac ID.
        /// </summary>
        internal static string strcpMAc {
            get {
                return ResourceManager.GetString("strcpMAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コンピューター名.
        /// </summary>
        internal static string strcpName {
            get {
                return ResourceManager.GetString("strcpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロセッサ.
        /// </summary>
        internal static string strcpProcess {
            get {
                return ResourceManager.GetString("strcpProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to インストールされているメモリ.
        /// </summary>
        internal static string strcpRam {
            get {
                return ResourceManager.GetString("strcpRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        internal static string strE {
            get {
                return ResourceManager.GetString("strE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたのメール アドレス.
        /// </summary>
        internal static string strEmail {
            get {
                return ResourceManager.GetString("strEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string strEnglish {
            get {
                return ResourceManager.GetString("strEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了.
        /// </summary>
        internal static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名.
        /// </summary>
        internal static string strFilename {
            get {
                return ResourceManager.GetString("strFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルの種類.
        /// </summary>
        internal static string strFileType {
            get {
                return ResourceManager.GetString("strFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキャンが終了.
        /// </summary>
        internal static string strFinished {
            get {
                return ResourceManager.GetString("strFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダーの場所.
        /// </summary>
        internal static string strFolder {
            get {
                return ResourceManager.GetString("strFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空き領域.
        /// </summary>
        internal static string strFree {
            get {
                return ResourceManager.GetString("strFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string strFrench {
            get {
                return ResourceManager.GetString("strFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche.
        /// </summary>
        internal static string strGerman {
            get {
                return ResourceManager.GetString("strGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ハード ドライブ.
        /// </summary>
        internal static string strHardware {
            get {
                return ResourceManager.GetString("strHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;タイプ別スキャン機能の使い方は。&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp10 {
            get {
                return ResourceManager.GetString("strHelp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;[種類でスキャン] &lt;/b&gt;をクリックしてすべてをスキャンおよび名前によってスキャンと同じ。ただし、注意をしてください。.
        /// </summary>
        internal static string strHelp11 {
            get {
                return ResourceManager.GetString("strHelp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;. 種類でスキャン
        ///&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp12 {
            get {
                return ResourceManager.GetString("strHelp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;left&quot;&gt;ファイル名を入力する必要はありません。ディスクを選択し、検索アイコンをク&lt;p&gt;&lt;/p&gt;
        ///リックすると、他のファイルの種類を検索するファイルの種類を表すアイコンを選択します。.&lt;/span&gt;.
        /// </summary>
        internal static string strHelp13 {
            get {
                return ResourceManager.GetString("strHelp13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo It アプリは、ファイルの削除後できるだけ早く実行すると最も効果的です。
        ///
        ///ファイルを削除すると、データは失われませんが、新しいファイルがハードディスクに書き込まれると、データが永久に上書きされ
        ///
        ///てリカバリが不可能になります.
        /// </summary>
        internal static string strHelp14 {
            get {
                return ResourceManager.GetString("strHelp14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;お問い合わせ :&lt;a href=&quot;mailto:support@ipcamsoft.com&quot;&gt;support@ipcamsoft.com&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;サポートページ：&lt;a href=&quot;http://ipcamsoft.com/support&quot; class=&quot;alert-link&quot;&gt;http://ipcamsoft.com/support&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;サポートチームに電子メールでお問い合わせください。: &lt;a href=&quot;mailto:support@ipcamsoft.com&quot;&gt;support@ipcamsoft.com&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string strHelp15 {
            get {
                return ResourceManager.GetString("strHelp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span align=&quot;center&quot;&gt;&lt;h3&gt;Undo It&lt;/h3&gt;&lt;/span&gt;&lt;/p&gt;
        ///Undo It は、迅速かつ簡単にあなたの削除されたファイルを回復するプログラムを元に戻す大きなファイルです。
        ///&lt;p&gt;&lt;/p&gt;
        ///このガイドは、簡単にアプリの使用を開始する方法を学習するのに役立ちます.
        /// </summary>
        internal static string strHelp16 {
            get {
                return ResourceManager.GetString("strHelp16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;すべてをスキャン  の使い方は。&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp4 {
            get {
                return ResourceManager.GetString("strHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;すべてをスキャン &lt;/b&gt; すべての削除済みファイルを検索します。.
        /// </summary>
        internal static string strHelp5 {
            get {
                return ResourceManager.GetString("strHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt; &gt; &lt;/b&gt; まず、&lt;b&gt; [すべてスキャン] &lt;/b&gt;ボタンをクリックします。&lt;/p&gt;
        ///&lt;b&gt; &gt; &lt;/b&gt; ディスクまたはフォルダーのいずれかで参照できます。同時にすべてのディスクをスキャンする場合は 
        ///&lt;p&gt;&lt;/p&gt;
        ///&lt;b&gt; [すべてのディスクの選択] &lt;/b&gt;ボックスをチェックします。&lt;p&gt;&lt;/p&gt;
        ///&lt;b&gt; &gt;&lt;/b&gt; &lt;b&gt;[スキャン]&lt;/b&gt;ボタンをクリックしてスキャンを開始します。
        ///&lt;p&gt;&lt;/p&gt;
        ///                         スキャンを停止したいときいつでも&lt;b&gt;[停止]&lt;/b&gt;ボタンをクリックします。
        ///&lt;p&gt;&lt;/p&gt;
        ///                         スキャンの完了後、ファイルをよりすばやく見つけることができる&lt;b&gt;検索&lt;/b&gt;ボックスにキーワード (ファイル名) を入力できます。
        ///&lt;p&gt;&lt;/p&gt;
        ///                         [システム ファイルという名前をシステム ファイルと不明なファイルの種類]、[検索] ボックスの横にあるボックスにチェック
        ///マークを表示する場合は。
        ///&lt;p&gt;&lt;/p&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strHelp6 {
            get {
                return ResourceManager.GetString("strHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;機能名でスキャンする方法は。&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp7 {
            get {
                return ResourceManager.GetString("strHelp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;名前でスキャン
        ///:&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp8 {
            get {
                return ResourceManager.GetString("strHelp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;left&quot;&gt;&lt;b&gt;[名前でスキャン]&lt;/b&gt; ボタンをクリックし、すべてボタンをスキャンとして同じ手順を行います。
        ///しかし、以下のようにいくつかの違いがあります。
        ///-スキャンする前にファイル名を入力します。
        ///(正しい名前が思い出せない場合入力するだけで同様のファイルをスキャンの名前の最初の文字) 
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strHelp9 {
            get {
                return ResourceManager.GetString("strHelp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;あなたのためのいくつかのアドバイス：&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpAD {
            get {
                return ResourceManager.GetString("strHelpAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+12&quot;&gt;お問い合わせ&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpCS {
            get {
                return ResourceManager.GetString("strHelpCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;ユーザーマニュアル&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpUS {
            get {
                return ResourceManager.GetString("strHelpUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string strJapanese {
            get {
                return ResourceManager.GetString("strJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 言語.
        /// </summary>
        internal static string strLanguage {
            get {
                return ResourceManager.GetString("strLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 後で.
        /// </summary>
        internal static string strLater {
            get {
                return ResourceManager.GetString("strLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 場所を選択します。.
        /// </summary>
        internal static string strlocation {
            get {
                return ResourceManager.GetString("strlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あなたは、元の場所と同じ場所にファイルを保存しようとしています。これは、回復エラーが発生し、データが完全に上書き。続行するよろしいですか。.
        /// </summary>
        internal static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回復が完了するまでお待ちください。.
        /// </summary>
        internal static string strMessage1 {
            get {
                return ResourceManager.GetString("strMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この機能を使用できるように登録してください。.
        /// </summary>
        internal static string strMessage10 {
            get {
                return ResourceManager.GetString("strMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回復が完了するまでお待ちください。.
        /// </summary>
        internal static string strMessage11 {
            get {
                return ResourceManager.GetString("strMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 続行するよろしいですか。.
        /// </summary>
        internal static string strMessage12 {
            get {
                return ResourceManager.GetString("strMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいバージョンが利用可能です。今すぐ更新しますか。.
        /// </summary>
        internal static string strMessage13 {
            get {
                return ResourceManager.GetString("strMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 申し訳ありませんが。スキャンを開始する前に、ファイルの種類を選択してください。.
        /// </summary>
        internal static string strMessage14 {
            get {
                return ResourceManager.GetString("strMessage14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキャンする前にファイル名を入力してください。.
        /// </summary>
        internal static string strMessage15 {
            get {
                return ResourceManager.GetString("strMessage15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキャンする前にドライブまたはドライブ上のフォルダーを選択してください。.
        /// </summary>
        internal static string strMessage16 {
            get {
                return ResourceManager.GetString("strMessage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名をここで検索します。.
        /// </summary>
        internal static string strMessage17 {
            get {
                return ResourceManager.GetString("strMessage17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;center&quot;&gt;アプリケーションは、スキャン プロセスでです。あなたはそれを停止してもよろしいですか。
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strMessage2 {
            get {
                return ResourceManager.GetString("strMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;center&quot;&gt;アプリケーションは、スキャン プロセスでです。あなたが終了してもよろしいですか。
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strMessage3 {
            get {
                return ResourceManager.GetString("strMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すみません。入力したメールアドレスの形式を確認してください！.
        /// </summary>
        internal static string strMessage4 {
            get {
                return ResourceManager.GetString("strMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シリアル番号フィールドは空にできません。.
        /// </summary>
        internal static string strMessage5 {
            get {
                return ResourceManager.GetString("strMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電子メール フィールド は空にできません。.
        /// </summary>
        internal static string strMessage6 {
            get {
                return ResourceManager.GetString("strMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to やり直してください。メール アドレスまたは指定したシリアル番号が正しくありません。.
        /// </summary>
        internal static string strMessage7 {
            get {
                return ResourceManager.GetString("strMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録完了.
        /// </summary>
        internal static string strMessage8 {
            get {
                return ResourceManager.GetString("strMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール アドレスとシリアル番号を入力してください。.
        /// </summary>
        internal static string strMessage9 {
            get {
                return ResourceManager.GetString("strMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最終更新日時.
        /// </summary>
        internal static string strModified {
            get {
                return ResourceManager.GetString("strModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名前.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シリアル番号.
        /// </summary>
        internal static string strNumber {
            get {
                return ResourceManager.GetString("strNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時間の始まり.
        /// </summary>
        internal static string strOption {
            get {
                return ResourceManager.GetString("strOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 過去 3 か月.
        /// </summary>
        internal static string strOption1 {
            get {
                return ResourceManager.GetString("strOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最後の週.
        /// </summary>
        internal static string strOption2 {
            get {
                return ResourceManager.GetString("strOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to から最終で次の項目をスキャンします。.
        /// </summary>
        internal static string strOption3 {
            get {
                return ResourceManager.GetString("strOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        internal static string strOption4 {
            get {
                return ResourceManager.GetString("strOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年間.
        /// </summary>
        internal static string strOption4a {
            get {
                return ResourceManager.GetString("strOption4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最後の.
        /// </summary>
        internal static string strOption5 {
            get {
                return ResourceManager.GetString("strOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オプション.
        /// </summary>
        internal static string strOption6 {
            get {
                return ResourceManager.GetString("strOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft PowerPoint.
        /// </summary>
        internal static string strP {
            get {
                return ResourceManager.GetString("strP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        internal static string strP3 {
            get {
                return ResourceManager.GetString("strP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4.
        /// </summary>
        internal static string strP4 {
            get {
                return ResourceManager.GetString("strP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パス.
        /// </summary>
        internal static string strPath {
            get {
                return ResourceManager.GetString("strPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe PDF.
        /// </summary>
        internal static string strPD {
            get {
                return ResourceManager.GetString("strPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今すぐ購入します.
        /// </summary>
        internal static string strPurchase {
            get {
                return ResourceManager.GetString("strPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回復.
        /// </summary>
        internal static string strRecovering {
            get {
                return ResourceManager.GetString("strRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -登録します.
        /// </summary>
        internal static string strRegister {
            get {
                return ResourceManager.GetString("strRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スキャンする.
        /// </summary>
        internal static string strScan {
            get {
                return ResourceManager.GetString("strScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 検索.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サイズ.
        /// </summary>
        internal static string strSize {
            get {
                return ResourceManager.GetString("strSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string strSpanish {
            get {
                return ResourceManager.GetString("strSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止する.
        /// </summary>
        internal static string strStop {
            get {
                return ResourceManager.GetString("strStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止.
        /// </summary>
        internal static string strStopping {
            get {
                return ResourceManager.GetString("strStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 種類.
        /// </summary>
        internal static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用領域.
        /// </summary>
        internal static string strUsed {
            get {
                return ResourceManager.GetString("strUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word.
        /// </summary>
        internal static string strW {
            get {
                return ResourceManager.GetString("strW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string strWarning {
            get {
                return ResourceManager.GetString("strWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3 {
            get {
                object obj = ResourceManager.GetObject("types_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("types_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("types_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video_audio {
            get {
                object obj = ResourceManager.GetObject("video_audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
