//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoveryThisFile.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecoveryThisFile.Language.sp", typeof(sp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_blue_backgrounds_40_1920x1200_71456 {
            get {
                object obj = ResourceManager.GetObject("abstract_blue_backgrounds_40_1920x1200_71456", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_3 {
            get {
                object obj = ResourceManager.GetObject("all_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("all_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_black {
            get {
                object obj = ResourceManager.GetObject("all_x128_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button1 {
            get {
                object obj = ResourceManager.GetObject("button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chosse {
            get {
                object obj = ResourceManager.GetObject("chosse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Header {
            get {
                object obj = ResourceManager.GetObject("Header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img2 {
            get {
                object obj = ResourceManager.GetObject("img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img3 {
            get {
                object obj = ResourceManager.GetObject("img3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3 {
            get {
                object obj = ResourceManager.GetObject("name_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("name_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("name_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1 {
            get {
                object obj = ResourceManager.GetObject("option_x128_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1_black {
            get {
                object obj = ResourceManager.GetObject("option_x128_1_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1_hv {
            get {
                object obj = ResourceManager.GetObject("option_x128_1_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_1 {
            get {
                object obj = ResourceManager.GetObject("pc_x128_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_1_hv {
            get {
                object obj = ResourceManager.GetObject("pc_x128_1_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("pc_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scanner {
            get {
                object obj = ResourceManager.GetObject("scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screen {
            get {
                object obj = ResourceManager.GetObject("screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar todos los discos.
        /// </summary>
        internal static string strAlldisk {
            get {
                return ResourceManager.GetString("strAlldisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorar.
        /// </summary>
        internal static string strB {
            get {
                return ResourceManager.GetString("strB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Archivo.
        /// </summary>
        internal static string strButton {
            get {
                return ResourceManager.GetString("strButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperar Archivos....
        /// </summary>
        internal static string strButton1 {
            get {
                return ResourceManager.GetString("strButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurar Archivos.
        /// </summary>
        internal static string strButton2 {
            get {
                return ResourceManager.GetString("strButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bueno (no se detectó pérdida de datos).
        /// </summary>
        internal static string strChance {
            get {
                return ResourceManager.GetString("strChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bueno (los datos podrían estar sobrescritos).
        /// </summary>
        internal static string strChance1 {
            get {
                return ResourceManager.GetString("strChance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malo (los datos están parcialmente sobrescritos).
        /// </summary>
        internal static string strChance2 {
            get {
                return ResourceManager.GetString("strChance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malo (los datos están completamente sobrescritos).
        /// </summary>
        internal static string strChance3 {
            get {
                return ResourceManager.GetString("strChance3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconocido.
        /// </summary>
        internal static string strChance4 {
            get {
                return ResourceManager.GetString("strChance4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excelente.
        /// </summary>
        internal static string strChance5 {
            get {
                return ResourceManager.GetString("strChance5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oportunidades de Recuperación.
        /// </summary>
        internal static string strChances {
            get {
                return ResourceManager.GetString("strChances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elige el tipo de archive.
        /// </summary>
        internal static string strChoose {
            get {
                return ResourceManager.GetString("strChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de computadora.
        /// </summary>
        internal static string strcp {
            get {
                return ResourceManager.GetString("strcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta de Usuario.
        /// </summary>
        internal static string strcpAC {
            get {
                return ResourceManager.GetString("strcpAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac ID.
        /// </summary>
        internal static string strcpMAc {
            get {
                return ResourceManager.GetString("strcpMAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de computadora.
        /// </summary>
        internal static string strcpName {
            get {
                return ResourceManager.GetString("strcpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesador.
        /// </summary>
        internal static string strcpProcess {
            get {
                return ResourceManager.GetString("strcpProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memoria instalada.
        /// </summary>
        internal static string strcpRam {
            get {
                return ResourceManager.GetString("strcpRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        internal static string strE {
            get {
                return ResourceManager.GetString("strE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su email.
        /// </summary>
        internal static string strEmail {
            get {
                return ResourceManager.GetString("strEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string strEnglish {
            get {
                return ResourceManager.GetString("strEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salir.
        /// </summary>
        internal static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre de archivo.
        /// </summary>
        internal static string strFilename {
            get {
                return ResourceManager.GetString("strFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Archivo.
        /// </summary>
        internal static string strFileType {
            get {
                return ResourceManager.GetString("strFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Búsqueda finalizada...!.
        /// </summary>
        internal static string strFinished {
            get {
                return ResourceManager.GetString("strFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación de Carpeta.
        /// </summary>
        internal static string strFolder {
            get {
                return ResourceManager.GetString("strFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disponible.
        /// </summary>
        internal static string strFree {
            get {
                return ResourceManager.GetString("strFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string strFrench {
            get {
                return ResourceManager.GetString("strFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche.
        /// </summary>
        internal static string strGerman {
            get {
                return ResourceManager.GetString("strGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco Duro.
        /// </summary>
        internal static string strHardware {
            get {
                return ResourceManager.GetString("strHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;How to use Scan by types feature?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp10 {
            get {
                return ResourceManager.GetString("strHelp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haga clic en el botón Analizar por tipos y haga lo mismo que en Analizar todo y Analizar por nombre. 
        ///Sin embargo, tenga en cuenta:.
        /// </summary>
        internal static string strHelp11 {
            get {
                return ResourceManager.GetString("strHelp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Analizar por tipos:&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp12 {
            get {
                return ResourceManager.GetString("strHelp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span align=&quot;left&quot;&gt;No es necesario escribir el nombre de archivo. Simplemente seleccione el disco y seleccione el icono que representa para el tipo de archivo que desea encontrar o haga clic en el icono &lt;b&gt;selección&lt;/b&gt; para buscar otros tipos de archivo.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp13 {
            get {
                return ResourceManager.GetString("strHelp13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;La aplicación Undo It funciona mejor si se realiza lo antes posible después de la eliminación de archivos&lt;/p&gt;
        ///Cuando elimina un archivo, los datos no se pierden, pero los nuevos archivos que se escriben en el disco duro pueden sobrescribir sus datos de forma permanente, lo que hace imposible la recuperación..
        /// </summary>
        internal static string strHelp14 {
            get {
                return ResourceManager.GetString("strHelp14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Contactanos en: &lt;a href=&quot;mailto:support@ipcamsoft.com&quot;&gt;support@ipcamsoft.com&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Nuestra página de soporte: &lt;a href=&quot;http://ipcamsoft.com/support&quot; class=&quot;alert-link&quot;&gt;http://ipcamsoft.com/support&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Envíe un correo electrónico a nuestro equipo de soporte en: &lt;a href=&quot;mailto:support@ipcamsoft.com&quot;&gt;support@ipcamsoft.com&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string strHelp15 {
            get {
                return ResourceManager.GetString("strHelp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span align=&quot;center&quot;&gt;&lt;h3&gt;Undo It&lt;/h3&gt;&lt;/span&gt;&lt;/p&gt;
        ///Undo It es un gran programa de recuperación de archivos que le ayudará a recuperar los archivos eliminados de forma rápida y sencilla.
        ///
        ///Esta guía le ayudará a aprender cómo empezar a usar la aplicación fácilmente..
        /// </summary>
        internal static string strHelp16 {
            get {
                return ResourceManager.GetString("strHelp16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;¿Cómo usar la función de escanear todos?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp4 {
            get {
                return ResourceManager.GetString("strHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt; Analizar Todo&lt;/b&gt; Busca todos los archivos eliminados:.
        /// </summary>
        internal static string strHelp5 {
            get {
                return ResourceManager.GetString("strHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt; &gt;&lt;/b&gt; En primer lugar, haga clic en el botón &lt;b&gt; Analizar Todo&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt; &gt;&lt;/b&gt; Puedes navegar por uno de tus discos o carpetas. Marque la casilla &lt;b&gt;Seleccionar todos los Discos&lt;/b&gt; si desea analizar todos los discos a la vez.&lt;/p&gt;
        ///&lt;b&gt; &gt;&lt;/b&gt; Y haga clic en el botón &lt;b&gt;Analizar&lt;/b&gt; para empezar el análisis.
        ///&lt;div&gt;
        ///                         &lt;p&gt;Haga clic en el botón &lt;b&gt;Detener&lt;/b&gt; en cualquier momento cuando desee detener el análisis.&lt;/p&gt;
        ///                         Después de haber terminado de ana [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strHelp6 {
            get {
                return ResourceManager.GetString("strHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;Cómo utilizar la función Escanear por nombre?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp7 {
            get {
                return ResourceManager.GetString("strHelp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Analizar por nombre: :&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp8 {
            get {
                return ResourceManager.GetString("strHelp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;left&quot;&gt;Haga clic en el botón Analizar por nombre y siga los mismos pasos como en el botón Analizar todo. Pero existen algunas diferencias a continuación:
        ///	Escriba el nombre del archivo antes de analizar. (Si no puede recordar el nombre correcto, simplemente escriba la primera letra del nombre para analizar archivos similares)
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strHelp9 {
            get {
                return ResourceManager.GetString("strHelp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;Algunos buenos consejos para usted:&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpAD {
            get {
                return ResourceManager.GetString("strHelpAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+12&quot;&gt;Contáctenos:&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpCS {
            get {
                return ResourceManager.GetString("strHelpCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;Manual del usuario&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpUS {
            get {
                return ResourceManager.GetString("strHelpUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string strJapanese {
            get {
                return ResourceManager.GetString("strJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idiomas.
        /// </summary>
        internal static string strLanguage {
            get {
                return ResourceManager.GetString("strLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Después.
        /// </summary>
        internal static string strLater {
            get {
                return ResourceManager.GetString("strLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Location.
        /// </summary>
        internal static string strlocation {
            get {
                return ResourceManager.GetString("strlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Está tratando de guardar el archive en la misma ubicación con su antigua ubicación. Esto podría resultar en recuperación fallida y sobrescribir sus datos permanentemente.¿Seguro que quiere continuar?.
        /// </summary>
        internal static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere hasta que la recuperación haya finalizado.
        /// </summary>
        internal static string strMessage1 {
            get {
                return ResourceManager.GetString("strMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor regístrese para que pueda usar esta función.
        /// </summary>
        internal static string strMessage10 {
            get {
                return ResourceManager.GetString("strMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espere hasta que la recuperación haya finalizado.
        /// </summary>
        internal static string strMessage11 {
            get {
                return ResourceManager.GetString("strMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Seguro que quiere continuar?.
        /// </summary>
        internal static string strMessage12 {
            get {
                return ResourceManager.GetString("strMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva version disponible. ¿Quiere actualizar ahora?.
        /// </summary>
        internal static string strMessage13 {
            get {
                return ResourceManager.GetString("strMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo siento. Por favor selecciona el tipo de archivo antes de iniciar búsqueda.
        /// </summary>
        internal static string strMessage14 {
            get {
                return ResourceManager.GetString("strMessage14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Escriba el nombre del archivo antes de analizar!.
        /// </summary>
        internal static string strMessage15 {
            get {
                return ResourceManager.GetString("strMessage15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Selecciona un disco o carpeta en disco antes de analizar!.
        /// </summary>
        internal static string strMessage16 {
            get {
                return ResourceManager.GetString("strMessage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar por nombre de archivo aquí.
        /// </summary>
        internal static string strMessage17 {
            get {
                return ResourceManager.GetString("strMessage17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;center&quot;&gt;La aplicación está en proceso de búsqueda. ¿Seguro que quiere detenerla?
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strMessage2 {
            get {
                return ResourceManager.GetString("strMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;center&quot;&gt;La aplicación está en proceso de búsqueda. ¿Seguro que quiere salir?
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strMessage3 {
            get {
                return ResourceManager.GetString("strMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos. ¡Revise el formato de la dirección de email suministrada!.
        /// </summary>
        internal static string strMessage4 {
            get {
                return ResourceManager.GetString("strMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Campo número de serial no puede estar vacío!.
        /// </summary>
        internal static string strMessage5 {
            get {
                return ResourceManager.GetString("strMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo de email no puede estar vacío.
        /// </summary>
        internal static string strMessage6 {
            get {
                return ResourceManager.GetString("strMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intente de nuevo. La dirección de email o número de serial que suministró es incorrecto..
        /// </summary>
        internal static string strMessage7 {
            get {
                return ResourceManager.GetString("strMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro exitoso.
        /// </summary>
        internal static string strMessage8 {
            get {
                return ResourceManager.GetString("strMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduzca su email y número de serial.
        /// </summary>
        internal static string strMessage9 {
            get {
                return ResourceManager.GetString("strMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Modificación.
        /// </summary>
        internal static string strModified {
            get {
                return ResourceManager.GetString("strModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de serial.
        /// </summary>
        internal static string strNumber {
            get {
                return ResourceManager.GetString("strNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El inicio del tiempo.
        /// </summary>
        internal static string strOption {
            get {
                return ResourceManager.GetString("strOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimos tres meses.
        /// </summary>
        internal static string strOption1 {
            get {
                return ResourceManager.GetString("strOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semana pasada.
        /// </summary>
        internal static string strOption2 {
            get {
                return ResourceManager.GetString("strOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizar los siguientes elementos por su última modificación:.
        /// </summary>
        internal static string strOption3 {
            get {
                return ResourceManager.GetString("strOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to año.
        /// </summary>
        internal static string strOption4 {
            get {
                return ResourceManager.GetString("strOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to años.
        /// </summary>
        internal static string strOption4a {
            get {
                return ResourceManager.GetString("strOption4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Últimos.
        /// </summary>
        internal static string strOption5 {
            get {
                return ResourceManager.GetString("strOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones.
        /// </summary>
        internal static string strOption6 {
            get {
                return ResourceManager.GetString("strOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft PowerPoint.
        /// </summary>
        internal static string strP {
            get {
                return ResourceManager.GetString("strP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        internal static string strP3 {
            get {
                return ResourceManager.GetString("strP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4.
        /// </summary>
        internal static string strP4 {
            get {
                return ResourceManager.GetString("strP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruta.
        /// </summary>
        internal static string strPath {
            get {
                return ResourceManager.GetString("strPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe PDF.
        /// </summary>
        internal static string strPD {
            get {
                return ResourceManager.GetString("strPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprar ahora.
        /// </summary>
        internal static string strPurchase {
            get {
                return ResourceManager.GetString("strPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperando.
        /// </summary>
        internal static string strRecovering {
            get {
                return ResourceManager.GetString("strRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarse.
        /// </summary>
        internal static string strRegister {
            get {
                return ResourceManager.GetString("strRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analizar.
        /// </summary>
        internal static string strScan {
            get {
                return ResourceManager.GetString("strScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorar.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talla.
        /// </summary>
        internal static string strSize {
            get {
                return ResourceManager.GetString("strSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string strSpanish {
            get {
                return ResourceManager.GetString("strSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detener.
        /// </summary>
        internal static string strStop {
            get {
                return ResourceManager.GetString("strStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deteniendo.
        /// </summary>
        internal static string strStopping {
            get {
                return ResourceManager.GetString("strStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización.
        /// </summary>
        internal static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usado.
        /// </summary>
        internal static string strUsed {
            get {
                return ResourceManager.GetString("strUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word.
        /// </summary>
        internal static string strW {
            get {
                return ResourceManager.GetString("strW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia.
        /// </summary>
        internal static string strWarning {
            get {
                return ResourceManager.GetString("strWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3 {
            get {
                object obj = ResourceManager.GetObject("types_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("types_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("types_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap video_audio {
            get {
                object obj = ResourceManager.GetObject("video_audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
