//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoveryThisFile.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RecoveryThisFile.Language.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_3 {
            get {
                object obj = ResourceManager.GetObject("all_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("all_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap all_x128_black {
            get {
                object obj = ResourceManager.GetObject("all_x128_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button1 {
            get {
                object obj = ResourceManager.GetObject("button1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chosse {
            get {
                object obj = ResourceManager.GetObject("chosse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand {
            get {
                object obj = ResourceManager.GetObject("Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img1 {
            get {
                object obj = ResourceManager.GetObject("img1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img2 {
            get {
                object obj = ResourceManager.GetObject("img2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img3 {
            get {
                object obj = ResourceManager.GetObject("img3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3 {
            get {
                object obj = ResourceManager.GetObject("name_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("name_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap name_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("name_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1 {
            get {
                object obj = ResourceManager.GetObject("option_x128_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1_black {
            get {
                object obj = ResourceManager.GetObject("option_x128_1_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap option_x128_1_hv {
            get {
                object obj = ResourceManager.GetObject("option_x128_1_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_1 {
            get {
                object obj = ResourceManager.GetObject("pc_x128_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_1_hv {
            get {
                object obj = ResourceManager.GetObject("pc_x128_1_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pc_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("pc_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scanner {
            get {
                object obj = ResourceManager.GetObject("scanner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap screen {
            get {
                object obj = ResourceManager.GetObject("screen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner tous les disques.
        /// </summary>
        internal static string strAlldisk {
            get {
                return ResourceManager.GetString("strAlldisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feuilleter.
        /// </summary>
        internal static string strB {
            get {
                return ResourceManager.GetString("strB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récupérer le Fichier.
        /// </summary>
        internal static string strButton {
            get {
                return ResourceManager.GetString("strButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récupérer les Fichiers.
        /// </summary>
        internal static string strButton1 {
            get {
                return ResourceManager.GetString("strButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurer des fichiers.
        /// </summary>
        internal static string strButton2 {
            get {
                return ResourceManager.GetString("strButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon (aucune donnée perdue détectée).
        /// </summary>
        internal static string strChance {
            get {
                return ResourceManager.GetString("strChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon (les données peuvent être écrasées).
        /// </summary>
        internal static string strChance1 {
            get {
                return ResourceManager.GetString("strChance1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais (les données sont partiellement écrasées).
        /// </summary>
        internal static string strChance2 {
            get {
                return ResourceManager.GetString("strChance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvais (les données sont complètement écrasées).
        /// </summary>
        internal static string strChance3 {
            get {
                return ResourceManager.GetString("strChance3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconnu.
        /// </summary>
        internal static string strChance4 {
            get {
                return ResourceManager.GetString("strChance4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        internal static string strChance5 {
            get {
                return ResourceManager.GetString("strChance5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chances de Récupération.
        /// </summary>
        internal static string strChances {
            get {
                return ResourceManager.GetString("strChances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez le type de fichier.
        /// </summary>
        internal static string strChoose {
            get {
                return ResourceManager.GetString("strChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations sur l&apos;ordinateur.
        /// </summary>
        internal static string strcp {
            get {
                return ResourceManager.GetString("strcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte d&apos;utilisateur.
        /// </summary>
        internal static string strcpAC {
            get {
                return ResourceManager.GetString("strcpAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac ID.
        /// </summary>
        internal static string strcpMAc {
            get {
                return ResourceManager.GetString("strcpMAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;ordinateur.
        /// </summary>
        internal static string strcpName {
            get {
                return ResourceManager.GetString("strcpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processeur.
        /// </summary>
        internal static string strcpProcess {
            get {
                return ResourceManager.GetString("strcpProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mémoire installée.
        /// </summary>
        internal static string strcpRam {
            get {
                return ResourceManager.GetString("strcpRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Excel.
        /// </summary>
        internal static string strE {
            get {
                return ResourceManager.GetString("strE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre email.
        /// </summary>
        internal static string strEmail {
            get {
                return ResourceManager.GetString("strEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string strEnglish {
            get {
                return ResourceManager.GetString("strEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortie.
        /// </summary>
        internal static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nom de fichier.
        /// </summary>
        internal static string strFilename {
            get {
                return ResourceManager.GetString("strFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de fichier.
        /// </summary>
        internal static string strFileType {
            get {
                return ResourceManager.GetString("strFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numérisation terminée.
        /// </summary>
        internal static string strFinished {
            get {
                return ResourceManager.GetString("strFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement des dossiers.
        /// </summary>
        internal static string strFolder {
            get {
                return ResourceManager.GetString("strFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratuit.
        /// </summary>
        internal static string strFree {
            get {
                return ResourceManager.GetString("strFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string strFrench {
            get {
                return ResourceManager.GetString("strFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsche.
        /// </summary>
        internal static string strGerman {
            get {
                return ResourceManager.GetString("strGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disque dur.
        /// </summary>
        internal static string strHardware {
            get {
                return ResourceManager.GetString("strHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;Comment utiliser la fonction Numériser par types?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp10 {
            get {
                return ResourceManager.GetString("strHelp10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur le bouton Numériser par types et faites de même que Numériser tout et Numériser par nom.
        ///Cependant, veuillez noter:.
        /// </summary>
        internal static string strHelp11 {
            get {
                return ResourceManager.GetString("strHelp11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Numériser par types:&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp12 {
            get {
                return ResourceManager.GetString("strHelp12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span align=&quot;left&quot;&gt;Vous n&apos;avez pas besoin de taper le nom de fichier. Sélectionnez simplement le Disque et sélectionnez l&apos;icône qui représente le type de fichier que vous souhaitez trouver ou cliquez sur l&apos;icône &lt;b&gt;Choix&lt;/b&gt; pour trouver d&apos;autres types de fichiers.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp13 {
            get {
                return ResourceManager.GetString("strHelp13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; RecoveryThisFile app wurket it bêste as jo sa gau mooglik nei triem wiske wurde. &lt;/p&gt;
        ///As jo in triem fuortsmite, dan wurde de gegevens net ferlern - mar nije triemmen skreaun wurde op &apos;e hurde skiif kinne jo gegevens periodyte oerskriuwe, wêrtroch it werheljen ûnmooglik is..
        /// </summary>
        internal static string strHelp14 {
            get {
                return ResourceManager.GetString("strHelp14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Contactez-nous à: &lt;a href=&quot;mailto:support@ipcamsoft.com&quot;&gt;support@ipcamsoft.com&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Notre page de support: &lt;a href=&quot;http://ipcamsoft.com/support&quot; class=&quot;alert-link&quot;&gt;http://ipcamsoft.com/support&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Envoyez notre équipe de soutien à: &lt;a href=&quot;mailto:support@ipcamsoft.com&quot;&gt;support@ipcamsoft.com&lt;/a&gt;.&lt;/p&gt;.
        /// </summary>
        internal static string strHelp15 {
            get {
                return ResourceManager.GetString("strHelp15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span align=&quot;center&quot;&gt;&lt;h3&gt;Undo It&lt;/h3&gt;&lt;/span&gt;&lt;/p&gt;
        ///Undo It est un programme excellent de récupération de fichiers qui vous aidera à récupérer vos fichiers supprimés rapidement et facilement.
        ///
        ///Ce guide vous aidera à apprendre comment commencer à utiliser l&apos;application facilement..
        /// </summary>
        internal static string strHelp16 {
            get {
                return ResourceManager.GetString("strHelp16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;Comment utiliser la fonction Numériser Tout?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp4 {
            get {
                return ResourceManager.GetString("strHelp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Numériser Tout&lt;/b&gt; Recherchez tous les fichiers supprimés:.
        /// </summary>
        internal static string strHelp5 {
            get {
                return ResourceManager.GetString("strHelp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt; &gt;&lt;/b&gt; Tout d&apos;abord, cliquez sur le bouton &lt;b&gt;Numériser Tout&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;b&gt; &gt;&lt;/b&gt; Vous pouvez parcourir un de vos Disques ou Dossier. Cochez la case &lt;b&gt;Sélectionner Tous les Disques&lt;/b&gt; si vous souhaitez numériser tous vos disques à la fois.&lt;/p&gt;
        ///
        ///&lt;b&gt; &gt;&lt;/b&gt; Et puis cliquez sur le bouton &lt;b&gt;Numériser&lt;/b&gt; pour commencer la numérisation.
        ///&lt;div&gt;
        ///                         &lt;p&gt;Cliquez sur le bouton &lt;b&gt;Arrêt&lt;/b&gt; à tout moment lorsque vous souhaitez arrêter la numérisation.&lt;/p&gt;
        ///                        &lt;p&gt; A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string strHelp6 {
            get {
                return ResourceManager.GetString("strHelp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font size=&quot;+5&quot;&gt;Comment utiliser la fonction Scan by name?&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelp7 {
            get {
                return ResourceManager.GetString("strHelp7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Numériser par nom:&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string strHelp8 {
            get {
                return ResourceManager.GetString("strHelp8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;left&quot;&gt;Cliquez sur le bouton Numériser par nom et faites les mêmes étapes que le bouton Numériser tout. Mais il y a des différences comme suit:
        ///Tapez le nom du fichier avant la numérisation. (Si vous ne vous souvenez pas du nom correct, tapez simplement la première lettre du nom pour la numérisation de fichiers similaires)&lt;/span&gt;.
        /// </summary>
        internal static string strHelp9 {
            get {
                return ResourceManager.GetString("strHelp9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;Quelques conseils roulants pour vous:&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpAD {
            get {
                return ResourceManager.GetString("strHelpAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;Contactez nous&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpCS {
            get {
                return ResourceManager.GetString("strHelpCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;font color=&quot;#FFFFFF&quot; size=&quot;+6&quot;&gt;Manuel utilisateur&lt;/font&gt;&lt;/b&gt;.
        /// </summary>
        internal static string strHelpUS {
            get {
                return ResourceManager.GetString("strHelpUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string strJapanese {
            get {
                return ResourceManager.GetString("strJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to les langues.
        /// </summary>
        internal static string strLanguage {
            get {
                return ResourceManager.GetString("strLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus tard.
        /// </summary>
        internal static string strLater {
            get {
                return ResourceManager.GetString("strLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez un Lieu.
        /// </summary>
        internal static string strlocation {
            get {
                return ResourceManager.GetString("strlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous essayez de sauvegarder le fichier dans le même emplacement avec son ancien emplacement. Cela pourrait entraîner une échoué de la récupération et écraser vos données en permanence.Es-tu sur de vouloir continuer?.
        /// </summary>
        internal static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendez que le rétablissement soit terminé..
        /// </summary>
        internal static string strMessage1 {
            get {
                return ResourceManager.GetString("strMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;il vous plaît vous inscrire pour pouvoir utiliser cette fonctionnalité.
        /// </summary>
        internal static string strMessage10 {
            get {
                return ResourceManager.GetString("strMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendez que le rétablissement soit terminé..
        /// </summary>
        internal static string strMessage11 {
            get {
                return ResourceManager.GetString("strMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es-tu sur de vouloir continuer?.
        /// </summary>
        internal static string strMessage12 {
            get {
                return ResourceManager.GetString("strMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une nouvelle version est disponible. Voulez-vous mettre à jour maintenant?.
        /// </summary>
        internal static string strMessage13 {
            get {
                return ResourceManager.GetString("strMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pardon. S&apos;il vous plaît sélectionner le type de fichier avant de commencer à numériser!.
        /// </summary>
        internal static string strMessage14 {
            get {
                return ResourceManager.GetString("strMessage14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapez le nom du fichier avant de numériser!.
        /// </summary>
        internal static string strMessage15 {
            get {
                return ResourceManager.GetString("strMessage15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez un lecteur ou un dossier sur le lecteur avant la numérisation!.
        /// </summary>
        internal static string strMessage16 {
            get {
                return ResourceManager.GetString("strMessage16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche par nom de fichier ici.
        /// </summary>
        internal static string strMessage17 {
            get {
                return ResourceManager.GetString("strMessage17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;center&quot;&gt;L&apos;application est en cours de numérisation. Êtes-vous sûr de vouloir l&apos;arrêter?
        ///&lt;/span&gt;.
        /// </summary>
        internal static string strMessage2 {
            get {
                return ResourceManager.GetString("strMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span align=&quot;center&quot;&gt;L&apos;application est en cours de numérisation. Êtes-vous sûr de vouloir quitter?&lt;/span&gt;.
        /// </summary>
        internal static string strMessage3 {
            get {
                return ResourceManager.GetString("strMessage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pardon. Vérifiez le format de l&apos;adresse électronique saisie!.
        /// </summary>
        internal static string strMessage4 {
            get {
                return ResourceManager.GetString("strMessage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ de numéro de série ne peut pas être vide.
        /// </summary>
        internal static string strMessage5 {
            get {
                return ResourceManager.GetString("strMessage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ de l&apos;e-mail ne peut pas être vide.
        /// </summary>
        internal static string strMessage6 {
            get {
                return ResourceManager.GetString("strMessage6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez réessayer. L&apos;adresse e-mail ou le numéro de série que vous avez fourni n&apos;est pas correct..
        /// </summary>
        internal static string strMessage7 {
            get {
                return ResourceManager.GetString("strMessage7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription réussi.
        /// </summary>
        internal static string strMessage8 {
            get {
                return ResourceManager.GetString("strMessage8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez le mail et le numéro de série.
        /// </summary>
        internal static string strMessage9 {
            get {
                return ResourceManager.GetString("strMessage9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière Modification.
        /// </summary>
        internal static string strModified {
            get {
                return ResourceManager.GetString("strModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom.
        /// </summary>
        internal static string strName {
            get {
                return ResourceManager.GetString("strName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de série.
        /// </summary>
        internal static string strNumber {
            get {
                return ResourceManager.GetString("strNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le début du temps.
        /// </summary>
        internal static string strOption {
            get {
                return ResourceManager.GetString("strOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les trois derniers mois.
        /// </summary>
        internal static string strOption1 {
            get {
                return ResourceManager.GetString("strOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La semaine dernière.
        /// </summary>
        internal static string strOption2 {
            get {
                return ResourceManager.GetString("strOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numérisez les éléments suivants par dernière modification de:.
        /// </summary>
        internal static string strOption3 {
            get {
                return ResourceManager.GetString("strOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to année.
        /// </summary>
        internal static string strOption4 {
            get {
                return ResourceManager.GetString("strOption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dernières années.
        /// </summary>
        internal static string strOption4a {
            get {
                return ResourceManager.GetString("strOption4a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les.
        /// </summary>
        internal static string strOption5 {
            get {
                return ResourceManager.GetString("strOption5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string strOption6 {
            get {
                return ResourceManager.GetString("strOption6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft PowerPoint.
        /// </summary>
        internal static string strP {
            get {
                return ResourceManager.GetString("strP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP3.
        /// </summary>
        internal static string strP3 {
            get {
                return ResourceManager.GetString("strP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP4.
        /// </summary>
        internal static string strP4 {
            get {
                return ResourceManager.GetString("strP4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin d&apos;accès.
        /// </summary>
        internal static string strPath {
            get {
                return ResourceManager.GetString("strPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe PDF.
        /// </summary>
        internal static string strPD {
            get {
                return ResourceManager.GetString("strPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achetez maintenant.
        /// </summary>
        internal static string strPurchase {
            get {
                return ResourceManager.GetString("strPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récupération.
        /// </summary>
        internal static string strRecovering {
            get {
                return ResourceManager.GetString("strRecovering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S’inscrire.
        /// </summary>
        internal static string strRegister {
            get {
                return ResourceManager.GetString("strRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string strSave {
            get {
                return ResourceManager.GetString("strSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numériser.
        /// </summary>
        internal static string strScan {
            get {
                return ResourceManager.GetString("strScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chercher.
        /// </summary>
        internal static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille.
        /// </summary>
        internal static string strSize {
            get {
                return ResourceManager.GetString("strSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string strSpanish {
            get {
                return ResourceManager.GetString("strSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêtez.
        /// </summary>
        internal static string strStop {
            get {
                return ResourceManager.GetString("strStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt.
        /// </summary>
        internal static string strStopping {
            get {
                return ResourceManager.GetString("strStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string strType {
            get {
                return ResourceManager.GetString("strType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mettre à jour.
        /// </summary>
        internal static string strUpdate {
            get {
                return ResourceManager.GetString("strUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisé.
        /// </summary>
        internal static string strUsed {
            get {
                return ResourceManager.GetString("strUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word.
        /// </summary>
        internal static string strW {
            get {
                return ResourceManager.GetString("strW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string strWarning {
            get {
                return ResourceManager.GetString("strWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3 {
            get {
                object obj = ResourceManager.GetObject("types_x128_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3_black {
            get {
                object obj = ResourceManager.GetObject("types_x128_3_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap types_x128_3_hv {
            get {
                object obj = ResourceManager.GetObject("types_x128_3_hv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Untitled {
            get {
                object obj = ResourceManager.GetObject("Untitled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
